const Footer = () => {
    return (
        <div style={{
            minHeight: '20vh',
            background: '#eaa12f'
        }}>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Minus, officiis, praesentium. Accusamus alias, aut dolores impedit ipsa quia voluptatum! Accusantium architecto aut beatae delectus, dolores et ex excepturi harum hic incidunt inventore ipsum iste itaque labore laudantium nobis optio recusandae veniam voluptate voluptatem. Consequuntur dicta maiores non officiis possimus. Earum, minima, quam. Aperiam labore non quibusdam tenetur veniam. Accusantium at distinctio dolor, dolorem ducimus eius esse impedit in necessitatibus nihil odit optio quae qui, ratione recusandae, reprehenderit rerum sapiente similique tempora totam ut veniam veritatis! Architecto dolorem et itaque labore nam natus nemo numquam optio praesentium, rerum sed totam unde vel! Cum deleniti dicta dignissimos fugiat, impedit, incidunt inventore maxime nihil nulla rem reprehenderit temporibus veniam vitae? Aspernatur blanditiis, deserunt error fugiat ipsam odit perspiciatis sapiente sit voluptates. Ab aliquid consequuntur distinctio enim ex iste maiores omnis quibusdam, sed. A ad aliquam architecto assumenda esse ex excepturi exercitationem iste laborum magnam maiores, minima minus necessitatibus nemo odit provident quae quaerat quam quasi quidem quos sequi soluta tempora temporibus ut vel voluptates? Aperiam, aut consequatur corporis culpa cupiditate ex fugit, ipsa labore minima mollitia nesciunt nostrum numquam provident repudiandae sapiente. A amet corporis cum dicta dignissimos dolorem ducimus eligendi eos eum facere facilis fugit impedit in inventore ipsa ipsam ipsum itaque magnam maiores natus nostrum quae quis quisquam ratione reiciendis repellat repellendus reprehenderit sint sit sunt tenetur, unde velit vero? Amet inventore molestiae placeat quod rem, tempore unde ut? Accusantium aliquid aperiam delectus dicta, expedita ipsum laboriosam molestiae necessitatibus nihil, perspiciatis, similique vel. Aperiam cupiditate dolore doloremque earum error facilis illo incidunt iste labore molestias numquam odio provident quae quaerat quisquam reiciendis tenetur unde veritatis voluptate, voluptates? Blanditiis consectetur culpa deleniti distinctio, dolor ea est, et explicabo illum iste minima nemo obcaecati officiis quia repudiandae sed soluta sunt veniam vitae voluptatum.</div>
    )
};

export default Footer;
